// SPDX-License-Identifier: MIT


pragma solidity 0.7.0;

/* Dayswappers Referral Program of Era Swap Ecosystem
 @dev you can use Dayswappers smart contract to reward users on your platform*/
abstract contract Dayswappers {
    
    /*@dev use when you want to reward to the entire introducer chain of a user
     @notice being payable, you also need to send ES appropriately (on ESN, Ether is ES)
     @param _walletAddress: wallet address of current user
     @param _rewardRatio: percentages to divide reward into [liquid, prepaid, staking]*/
    function payToTree(address _networker, uint256[3] memory _rewardRatio) external payable virtual;
    
    /* @dev use when you want to reward only to the introducer of a user
     @notice being payable, you also need to send ES appropriately (on ESN, Ether is ES)
     @param _walletAddress: wallet address of current user
     @param _rewardRatio: percentages to divide reward into [liquid, prepaid, staking]*/
    function payToIntroducer(address _networker, uint256[3] memory _rewardRatio) external payable virtual;
    
    // @dev use when you want to report volume generated by a user on your platform
    function reportVolume(address _networker, uint256 _amount) external virtual;
}